###
GET http://localhost:8080/protected
Authorization: Basic YWRtaW46MTIz


### Login request
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### 
GET http://localhost:8080/stream
Content-Type: text/plain

###
GET http://localhost:8080/stream-json
Content-Type: application/json

###
GET http://localhost:8080/stream/sse


###
GET http://localhost:8080/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaXNfYWRtaW4iOnRydWUsImV4cCI6MTc3MDQyODg0OSwiaWF0IjoxNzcwMzQyNDQ5fQ.xcgrLOjdncFGUJOwOQCdekzBwdjTbrWWCA250ZgWfwE

###
GET http://localhost:8080/api/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NzA0MjkyOTIsImlhdCI6MTc3MDM0Mjg5Mn0.3-1vTiF5Oe3ogAIJscJznQrIes44syHCKc2nCQd13zA



### Health check
GET http://localhost:8080/

### Get all users
GET http://localhost:8080/users
Accept: application/json

### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 3,
  "name": "Bob"
}

### Get user by ID (if you implement it later)
GET http://localhost:8080/users/1
Accept: application/json

### Update user (if you implement)
PUT http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "Updated Name"
}

### Delete user (if you implement)
DELETE http://localhost:8080/users/2
